### ISSUE TITLE
change to plot_result function 

### ISSUE THREAD

**Issue by cbtohill** [astroferreira/galclean#3]
The input variable seg_map to the plot_result function is missing from the notebook example however is not needed as an input as it is the first two inputs (ori_img, segmented_img) subtracted so can be created within the function itself. 

Have defined `residual = ori_img-segmented_img` within the function so can remove seg_map from function and plot residual instead.

**Comment by astroferreira** [comment]
Thanks @cbtohill for pointing it out. Your PullRequest (#5) solve this and it is now merged to with master.
